package edu.bu.cs411.group10.curre.run;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
public class RunRepositoryTest {
    @Autowired
    private RunRepository runRepository;

    @Test
    public void testSaveAndRetrieveRun(){
        Run newRun = new Run();
        newRun.setStartedAt(1711234567000L);
        newRun.setEndedAt(1711235167000L);
        newRun.setDistanceMiles(1.5);
        newRun.setDurationSeconds(900);
        newRun.setAvgPaceSecsPerMile(600.0);
        newRun.setCalories(5);

        Run savedrun = runRepository.save(newRun);
        assertNotNull(savedrun.getId(), "The saved run should have an ID generated by the database.");
        List<Run> allRuns = runRepository.findAll();
        assertFalse(allRuns.isEmpty(), "There should be at least one run in the database.");

    }
}
